### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by omgjasonbourne** [dragonfire535/xiaobot#2]
I receive this error when I try to start the bot (I use Atom)

```
Error: Cannot find module './eastereggs.json'
    at Function.Module._resolveFilename (module.js:470:15)
    at Function.Module._load (module.js:418:25)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\---\test\commands\random\easteregg.js:2:20)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
```

**Comment by dragonfire535** [comment]
This is because I `gitignore` the eastereggs file to prevent users from finding them out by cheating. You'll have to make your own, it's a simple JSON file containing an object with each easter egg:

```js
{
    "egg1": "Result",
    "egg2": "Redult"
}
```

Also, I recommend you `git pull` before doing that as I just pushed a rather large update.
